plugins {
    id 'com.android.application'
}

android {
    namespace 'fr.francoisbasset.pokecross'
    compileSdk 35

    defaultConfig {
        applicationId 'fr.francoisbasset.pokecross'
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName '1.0.1'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
